"""人工整理的中文精选免费资源。

为什么单独维护这份数据（而不是只抓 free-for-dev）：
  1. 国内平台 free-for-dev 一条都没有 —— 智谱、百炼、讯飞、腾讯混元、硅基流动
     这些国内免费额度对学生党最实用，但那份英文清单完全没收录。
  2. free-for-dev 只有英文描述，且需要自己 Ctrl+F 翻；这里每条都写了
     「免费额度 / 要求 / 国内能不能用 / 有什么坑」四个中国用户最关心的字段。
  3. 人工核实过的条目可以标注可信度，避免「注册完发现要绑卡」这种浪费。

数据整理时间：2026-09。免费政策随时会变，请以官网为准。
每条都带 `reviewed` 字段记录核对日期。
"""

from __future__ import annotations

# ── 分类（中文名 + 排序权重，权重小的排前面）────────────────────────────
CATEGORIES: list[tuple[str, str]] = [
    ("student", "学生专属福利"),
    ("ai-api", "AI 大模型 API"),
    ("ai-compute", "AI 算力 / GPU"),
    ("cloud", "云服务器 / 免费额度"),
    ("hosting", "网站托管 / 部署"),
    ("database", "数据库"),
    ("storage", "对象存储 / 图床"),
    ("cdn-dns", "域名 / DNS / CDN"),
    ("cicd", "CI/CD / 代码托管"),
    ("monitor", "监控 / 告警 / 日志"),
    ("email", "邮件发送"),
    ("api-other", "其他免费 API"),
    ("auth", "登录 / 认证"),
    ("devtool", "开发工具 / 其他"),
]

# ── 标签（用于筛选，中文）────────────────────────────────────────────────
# need_card   需信用卡    need_id   需实名认证    no_card   免信用卡
# cn_ok       国内直连    cn_partial 部分可用     cn_no     需梯子
# permanent   长期免费    limited   限时赠送

ENTRIES: list[dict] = [
    # ══════════════════ AI 大模型 API（用户最关心）══════════════════
    {
        "id": "zhipu",
        "name": "智谱 AI（GLM）",
        "category": "ai-api",
        "summary": "国内大模型第一梯队，注册即送 2000 万 tokens 体验包，编程能力强的 GLM 系列。",
        "quota": "新用户 2000 万 tokens（含 1200 万 glm-4.5-air + 600 万 glm-4.6v + 200 万通用）",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "3 个月有效",
        "url": "https://www.bigmodel.cn",
        "tips": "注册后在「财务 → 资源包」查看剩余额度；优先消耗快过期的。",
        "tags": "ai 大模型 llm api 免费 tokens 国产 glm 编程",
        "reviewed": "2026-09",
    },
    {
        "id": "aliyun-bailian",
        "name": "阿里云百炼（DashScope）",
        "category": "ai-api",
        "summary": "模型最全的国内平台，包含 qwen、deepseek 系列，新用户每个模型 100 万 tokens 免费额度。",
        "quota": "各模型 100 万 tokens，有效期 90 天",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "90 天",
        "url": "https://bailian.console.aliyun.com",
        "tips": "控制台「模型用量 → 免费额度」可看总额度与到期时间；务必打开「用完即停」避免超额扣费。",
        "tags": "ai 大模型 llm api qwen 通义 deepseek 免费 tokens 阿里云",
        "reviewed": "2026-09",
    },
    {
        "id": "xfyun-spark",
        "name": "讯飞星火",
        "category": "ai-api",
        "summary": "注册直接领 500 万 tokens，中文问答和数理逻辑表现好。",
        "quota": "500 万 tokens",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "以官网为准",
        "url": "https://www.xfyun.cn",
        "tips": "首页「星火大模型」入口领取。",
        "tags": "ai 大模型 llm api 星火 spark 免费 tokens 科大讯飞",
        "reviewed": "2026-09",
    },
    {
        "id": "tencent-hunyuan",
        "name": "腾讯云混元",
        "category": "ai-api",
        "summary": "实名后领 100 万 tokens 混元资源包，有效期长达 1 年（国内少见的长有效期）。",
        "quota": "混元大模型 100 万 tokens + 混元 embedding 100 万 tokens",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "1 年",
        "url": "https://console.cloud.tencent.com",
        "tips": "控制台控制台「资源包管理」查看；适合长期慢速使用。",
        "tags": "ai 大模型 llm api 混元 hunyuan 免费 tokens 腾讯云",
        "reviewed": "2026-09",
    },
    {
        "id": "moonshot-kimi",
        "name": "月之暗面 Kimi",
        "category": "ai-api",
        "summary": "长文本处理是业界标杆，注册完成个人认证送 15 元代金券。",
        "quota": "15 元赠送金额",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "约 3 个月",
        "url": "https://platform.moonshot.cn",
        "tips": "右上角「用户中心 → 组织认证」完成个人认证后自动到账。",
        "tags": "ai 大模型 llm api kimi 月之暗面 moonshot 免费 长文本",
        "reviewed": "2026-09",
    },
    {
        "id": "minimax",
        "name": "MiniMax",
        "category": "ai-api",
        "summary": "多模态能力强（文本/语音/视频/图像），实名后送 15 元代金券。",
        "quota": "15 元代金券",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "约 2 个月",
        "url": "https://platform.minimaxi.com",
        "tips": "完成个人实名认证后自动发放。",
        "tags": "ai 大模型 llm api minimax 语音 多模态 免费",
        "reviewed": "2026-09",
    },
    {
        "id": "siliconflow",
        "name": "硅基流动 SiliconFlow",
        "category": "ai-api",
        "summary": "一个 API 调全网主流开源模型（DeepSeek / Qwen / GLM / Kimi），实名送 16 元通用券。",
        "quota": "16 元平台通用代金券",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "180 天",
        "url": "https://cloud.siliconflow.cn",
        "tips": "首次实名认证后领取；适合横向对比不同模型效果。",
        "tags": "ai 大模型 llm api 硅基流动 siliconflow 免费 聚合",
        "reviewed": "2026-09",
    },
    {
        "id": "scnet",
        "name": "超算互联网",
        "category": "ai-api",
        "summary": "国家超算平台，新人送 100 万 tokens。",
        "quota": "100 万 tokens",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "1 个月",
        "url": "https://www.scnet.cn",
        "tips": "首次登录领取；模型选择较少。",
        "tags": "ai 大模型 llm api 超算 免费 tokens",
        "reviewed": "2026-09",
    },
    {
        "id": "google-gemini-free",
        "name": "Google Gemini API（免费层）",
        "category": "ai-api",
        "summary": "海外最实用的免费大模型 API，有长期免费层（不是赠送额度，是持续免费）。",
        "quota": "免费层：每分钟 15 次请求 / 每天 1500 次（Gemini Flash 系列）",
        "requirements": ["需谷歌账号", "免信用卡"],
        "china": "cn_no",
        "expiry": "长期免费",
        "url": "https://ai.google.dev",
        "tips": "国内需自行解决网络；免费层数据可能被用于产品改进，别传敏感内容。",
        "tags": "ai 大模型 llm api gemini google 免费 免费层",
        "reviewed": "2026-09",
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "category": "ai-api",
        "summary": "全球最大的模型聚合网关，里面有 20+ 个完全免费的模型，一个 key 全都能调。",
        "quota": "约 28 个模型的免费额度（含 MiniMax、Step 等）",
        "requirements": ["免信用卡"],
        "china": "cn_no",
        "expiry": "长期（以平台为准）",
        "url": "https://openrouter.ai",
        "tips": "站内搜 'free' 可筛出所有免费模型；免费模型有速率限制。",
        "tags": "ai 大模型 llm api openrouter 聚合 免费模型",
        "reviewed": "2026-09",
    },
    {
        "id": "github-models",
        "name": "GitHub Models",
        "category": "ai-api",
        "summary": "用你已有的 GitHub 账号直接调 GPT-5 / GPT-4o 等模型，不用绑卡、不用另外注册。",
        "quota": "免费额度（按模型有速率限制）",
        "requirements": ["需 GitHub 账号", "免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://github.com/marketplace/models",
        "tips": "用 GitHub Token 直接调，是对国内用户最省事的海外模型入口之一。",
        "tags": "ai 大模型 llm api github gpt 免费 免绑卡",
        "reviewed": "2026-09",
    },
    {
        "id": "groq",
        "name": "Groq",
        "category": "ai-api",
        "summary": "推理速度极快的免费 API，不需要绑卡，适合做实时应用。",
        "quota": "免费层（有每分钟/每天速率限制）",
        "requirements": ["免信用卡"],
        "china": "cn_no",
        "expiry": "长期",
        "url": "https://console.groq.com",
        "tips": "超限会返回 429；模型含 llama、qwen 等开源模型。",
        "tags": "ai 大模型 llm api groq 免费 快速 推理",
        "reviewed": "2026-09",
    },
    {
        "id": "huggingface-inference",
        "name": "Hugging Face Inference API",
        "category": "ai-api",
        "summary": "几千个开源模型的免费推理额度，做实验最方便。",
        "quota": "每月一定量的免费调用",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://huggingface.co/inference-api",
        "tips": "部分模型需要排队；国内访问速度一般。",
        "tags": "ai 大模型 llm api huggingface 免费 开源模型",
        "reviewed": "2026-09",
    },

    # ══════════════════ AI 算力 / GPU ══════════════════
    {
        "id": "kaggle-gpu",
        "name": "Kaggle（免费 GPU）",
        "category": "ai-compute",
        "summary": "谷歌旗下，验证手机号后每周 30 小时 P100 或 2×T4 GPU，炼丹党零成本首选。",
        "quota": "每周 30 小时 GPU；通过身份验证后还有 TPU v3-8 每周 20 小时",
        "requirements": ["需手机验证", "免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.kaggle.com",
        "tips": "单次会话最长 12 小时；数据需要放 Kaggle Dataset 里。",
        "tags": "ai gpu 算力 免费 训练 深度学习 kaggle",
        "reviewed": "2026-09",
    },
    {
        "id": "google-colab",
        "name": "Google Colab",
        "category": "ai-compute",
        "summary": "最经典的免费 Jupyter 环境，偶尔能白嫖到 T4/P100。",
        "quota": "免费 GPU（受限，不保证类型）",
        "requirements": ["需谷歌账号", "免信用卡"],
        "china": "cn_no",
        "expiry": "长期",
        "url": "https://colab.research.google.com",
        "tips": "免费档有闲置断连机制；重要结果记得存 Google Drive。",
        "tags": "ai gpu 算力 免费 notebook jupyter colab 深度学习",
        "reviewed": "2026-09",
    },

    # ══════════════════ 云服务器 / 免费额度 ══════════════════
    {
        "id": "oracle-always-free",
        "name": "Oracle Cloud Always Free",
        "category": "cloud",
        "summary": "永久免费云主机里的天花板：2 核 ARM + 12GB 内存（2026-08 后下调），加 200GB 块存储、每月 10TB 出流量。",
        "quota": "A1 ARM 2 OCPU / 12GB + 2 台 AMD 1/8 OCPU / 1GB + 200GB 块存储 + 10TB/月出流量",
        "requirements": ["需信用卡验证（不扣费）"],
        "china": "cn_partial",
        "expiry": "永久免费",
        "url": "https://www.oracle.com/cloud/free/",
        "tips": "① 免费档 ARM 容量紧张，常需抢；② 闲置实例会被回收，跑个定时任务保活；③ 必须绑卡验证身份。",
        "tags": "云服务器 免费 vps 主机 永久 甲骨文 oracle arm",
        "reviewed": "2026-09",
    },
    {
        "id": "gcp-free-tier",
        "name": "Google Cloud 免费层",
        "category": "cloud",
        "summary": "1 台 e2-micro 永久免费（限特定区域），外加 BigQuery 每月 1TB 查询、Cloud Run 每月 200 万请求。",
        "quota": "e2-micro 1 台永久免费；Cloud Run 200 万次/月；BigQuery 1TB 查询/月",
        "requirements": ["需信用卡"],
        "china": "cn_no",
        "expiry": "永久（部分服务限区域）",
        "url": "https://cloud.google.com/free",
        "tips": "e2-micro 仅限 us-west1 / us-central1 / us-east1；出网流量要另算，注意流量费。",
        "tags": "云服务器 免费 vps 主机 gcp google 永久",
        "reviewed": "2026-09",
    },
    {
        "id": "aws-free-tier",
        "name": "AWS 免费层",
        "category": "cloud",
        "summary": "新账号 12 个月 t2.micro 750 小时/月 + Lambda 每月 100 万次 + S3 5GB。",
        "quota": "EC2 t2.micro 750 小时/月（12 个月）；Lambda 100 万次/月；DynamoDB 25GB",
        "requirements": ["需信用卡"],
        "china": "cn_partial",
        "expiry": "12 个月（部分永久）",
        "url": "https://aws.amazon.com/free/",
        "tips": "12 个月到期后会自动转按量计费，务必设日历提醒；这是最容易产生意外账单的一家。",
        "tags": "云服务器 免费 vps 主机 aws 亚马逊 试用",
        "reviewed": "2026-09",
    },
    {
        "id": "aliyun-trial",
        "name": "阿里云新用户试用",
        "category": "cloud",
        "summary": "新用户可领 1 核 2G 云服务器试用（通常 1~3 个月），经常有 99 元/年的轻量服务器活动。",
        "quota": "1 核 2G 试用 1~3 个月；轻量应用服务器常有低价年付活动",
        "requirements": ["需实名"],
        "china": "cn_ok",
        "expiry": "限时（1~3 个月）",
        "url": "https://free.aliyun.com",
        "tips": "到期会自动续费转付费，一定提前取消；学生可另看「阿里云高校计划」。",
        "tags": "云服务器 免费 vps 主机 阿里云 试用 国内",
        "reviewed": "2026-09",
    },
    {
        "id": "tencent-trial",
        "name": "腾讯云新用户试用",
        "category": "cloud",
        "summary": "新用户免费试用额度，轻量应用服务器经常有学生优惠。",
        "quota": "新用户试用额度和活动价（以官网为准）",
        "requirements": ["需实名"],
        "china": "cn_ok",
        "expiry": "限时",
        "url": "https://cloud.tencent.com/act/free",
        "tips": "同样注意到期自动续费；「腾讯云+校园」有学生专属优惠。",
        "tags": "云服务器 免费 vps 主机 腾讯云 试用 国内 学生",
        "reviewed": "2026-09",
    },
    {
        "id": "huawei-trial",
        "name": "华为云新用户试用",
        "category": "cloud",
        "summary": "新用户免费试用，部分产品有长期免费额度。",
        "quota": "以官网活动为准",
        "requirements": ["需实名"],
        "china": "cn_ok",
        "expiry": "限时",
        "url": "https://www.huaweicloud.com/free/",
        "tips": "注意到期续费；华为云对教育/学生场景有额外活动。",
        "tags": "云服务器 免费 vps 主机 华为云 试用 国内",
        "reviewed": "2026-09",
    },
    {
        "id": "cloudflare-workers",
        "name": "Cloudflare Workers",
        "category": "cloud",
        "summary": "边缘 Serverless，每天 10 万次请求免费，不需要信用卡。",
        "quota": "10 万次请求/天",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://workers.cloudflare.com",
        "tips": "和 Cloudflare 其他免费产品（R2 / D1 / Pages / Tunnel）组合起来能撑起一整套个人基础设施。",
        "tags": "云服务器 serverless 免费 边缘 cloudflare workers 无服务器",
        "reviewed": "2026-09",
    },

    # ══════════════════ 网站托管 / 部署 ══════════════════
    {
        "id": "vercel",
        "name": "Vercel",
        "category": "hosting",
        "summary": "前端项目免费部署，每月 100GB 流量，自动 CI/CD + 预览环境。",
        "quota": "每月 100GB 流量；个人项目免费",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://vercel.com",
        "tips": "国内访问其默认域名可能较慢，建议绑自己的域名。",
        "tags": "网站托管 部署 免费 前端 vercel 静态",
        "reviewed": "2026-09",
    },
    {
        "id": "netlify",
        "name": "Netlify",
        "category": "hosting",
        "summary": "静态站免费托管，每月 100GB 流量，和 Vercel 类似。",
        "quota": "100GB 流量/月，300 构建分钟/月",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.netlify.com",
        "tips": "表单、身份认证等增值功能也有免费额度。",
        "tags": "网站托管 部署 免费 静态 netlify",
        "reviewed": "2026-09",
    },
    {
        "id": "cloudflare-pages",
        "name": "Cloudflare Pages",
        "category": "hosting",
        "summary": "静态站托管，流量不限，每月 500 次构建。",
        "quota": "无限流量；500 次构建/月；100 个自定义域名",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://pages.cloudflare.com",
        "tips": "配合 Cloudflare CDN，国内访问通常比 Vercel 顺畅一些。",
        "tags": "网站托管 部署 免费 静态 cloudflare pages",
        "reviewed": "2026-09",
    },
    {
        "id": "github-pages",
        "name": "GitHub Pages",
        "category": "hosting",
        "summary": "最老牌的免费静态托管，推代码就发布，适合放文档和博客。",
        "quota": "公开仓库无限；每月 100GB 流量软限制",
        "requirements": ["需 GitHub 账号", "免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://pages.github.com",
        "tips": "国内访问 github.io 不稳定，建议绑自定义域名 + CDN。",
        "tags": "网站托管 部署 免费 静态 github pages 博客",
        "reviewed": "2026-09",
    },
    {
        "id": "render",
        "name": "Render",
        "category": "hosting",
        "summary": "免费 Web Service（有冷启动），适合跑个人后端服务。",
        "quota": "免费实例（闲置会休眠）",
        "requirements": ["免信用卡"],
        "china": "cn_no",
        "expiry": "长期",
        "url": "https://render.com",
        "tips": "免费实例闲置 15 分钟休眠，首次访问会慢十几秒。",
        "tags": "网站托管 部署 免费 后端 render paas",
        "reviewed": "2026-09",
    },
    {
        "id": "railway",
        "name": "Railway",
        "category": "hosting",
        "summary": "每月 5 美元免费额度，适合小型后端服务。",
        "quota": "每月 $5 额度",
        "requirements": ["需信用卡"],
        "china": "cn_no",
        "expiry": "每月重置",
        "url": "https://railway.app",
        "tips": "额度用完服务会停，不会自动扣费（但仍建议绑卡后设提醒）。",
        "tags": "网站托管 部署 免费 后端 railway paas",
        "reviewed": "2026-09",
    },

    # ══════════════════ 数据库 ══════════════════
    {
        "id": "supabase",
        "name": "Supabase",
        "category": "database",
        "summary": "开源版 Firebase，免费 PostgreSQL 500MB，还带认证、存储、实时订阅。",
        "quota": "500MB 数据库 + 5GB 带宽；最多 2 个项目",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://supabase.com",
        "tips": "免费项目闲置 7 天会被暂停，需要手动恢复。",
        "tags": "数据库 免费 postgresql postgres supabase 后端",
        "reviewed": "2026-09",
    },
    {
        "id": "neon",
        "name": "Neon",
        "category": "database",
        "summary": "Serverless PostgreSQL，免费 0.5GB，支持数据库分支（像 git 分支一样）。",
        "quota": "0.5GB 存储，10 个项目",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://neon.tech",
        "tips": "计算实例会休眠，冷启动有延迟。",
        "tags": "数据库 免费 postgresql serverless neon",
        "reviewed": "2026-09",
    },
    {
        "id": "mongodb-atlas",
        "name": "MongoDB Atlas",
        "category": "database",
        "summary": "行业标准的免费 MongoDB，512MB 永久免费。",
        "quota": "512MB 存储",
        "requirements": ["需信用卡（部分区域不需要）"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.mongodb.com/atlas",
        "tips": "选免费 M0 集群；注意默认开放 IP 白名单有安全风险，记得收紧。",
        "tags": "数据库 免费 mongodb nosql atlas",
        "reviewed": "2026-09",
    },
    {
        "id": "redis-cloud",
        "name": "Redis Cloud",
        "category": "database",
        "summary": "免费 30MB Redis，够做缓存和队列测试。",
        "quota": "30MB 内存",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://redis.io/cloud/",
        "tips": "容量很小，只适合开发/测试。",
        "tags": "数据库 免费 redis 缓存",
        "reviewed": "2026-09",
    },
    {
        "id": "upstash",
        "name": "Upstash",
        "category": "database",
        "summary": "Serverless Redis + Kafka，按请求计费，免费层够个人项目用。",
        "quota": "Redis 免费层 + Kafka 免费层",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://upstash.com",
        "tips": "按请求计费的模式，免费额度用完会拒绝而不是扣费。",
        "tags": "数据库 免费 redis kafka serverless upstash",
        "reviewed": "2026-09",
    },
    {
        "id": "turso",
        "name": "Turso",
        "category": "database",
        "summary": "边缘 SQLite，免费 9GB 存储，适合轻量应用。",
        "quota": "9GB 存储",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://turso.tech",
        "tips": "基于 SQLite，迁移成本低。",
        "tags": "数据库 免费 sqlite 边缘 turso",
        "reviewed": "2026-09",
    },
    {
        "id": "cloudflare-d1",
        "name": "Cloudflare D1",
        "category": "database",
        "summary": "Cloudflare 家的边缘 SQLite 数据库，免费 5GB。",
        "quota": "5GB 存储",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://developers.cloudflare.com/d1/",
        "tips": "和 Workers 配合最顺手。",
        "tags": "数据库 免费 sqlite cloudflare d1 边缘",
        "reviewed": "2026-09",
    },

    # ══════════════════ 对象存储 / 图床 ══════════════════
    {
        "id": "cloudflare-r2",
        "name": "Cloudflare R2",
        "category": "storage",
        "summary": "唯一真正做到出站流量免费的对象存储：10GB 存储 + 出站流量 0 费用。",
        "quota": "10GB 存储/月，出站流量免费",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.cloudflare.com/r2/",
        "tips": "兼容 S3 协议，可以直接套用现有 S3 代码；个人项目几乎不可能超。",
        "tags": "对象存储 免费 图床 s3 cloudflare r2 流量",
        "reviewed": "2026-09",
    },
    {
        "id": "backblaze-b2",
        "name": "Backblaze B2",
        "category": "storage",
        "summary": "10GB 免费存储 + 每天 10GB 出站流量，比 R2 存储更大。",
        "quota": "10GB 存储 + 10GB/天出站",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.backblaze.com/b2/cloud-storage.html",
        "tips": "和 Cloudflare 互联（Bandwidth Alliance）后出站也免费，是 R2 之外的好选择。",
        "tags": "对象存储 免费 图床 backblaze b2 备份",
        "reviewed": "2026-09",
    },
    {
        "id": "qiniu-free",
        "name": "七牛云免费额度",
        "category": "storage",
        "summary": "国内对象存储 + CDN，有长期免费额度（10GB 存储 + 每月 10GB CDN 流量）。",
        "quota": "10GB 存储 + 每月 10GB CDN 流量（以官网为准）",
        "requirements": ["需实名"],
        "china": "cn_ok",
        "expiry": "长期免费额度",
        "url": "https://www.qiniu.com",
        "tips": "国内做图床/CDN 最省事的选择之一；注意测试域名每月有流量限制。",
        "tags": "对象存储 免费 图床 cdn 七牛 国内",
        "reviewed": "2026-09",
    },
    {
        "id": "smms",
        "name": "SM.MS 图床",
        "category": "storage",
        "summary": "老牌免费图床，注册后直接用，适合 Markdown 配图。",
        "quota": "免费额度（有速率限制）",
        "requirements": ["免信用卡"],
        "china": "cn_ok",
        "expiry": "长期",
        "url": "https://sm.ms",
        "tips": "免费图床有失效风险，重要的图别只放这里。",
        "tags": "图床 免费 图片 存储 smms markdown",
        "reviewed": "2026-09",
    },

    # ══════════════════ 域名 / DNS / CDN ══════════════════
    {
        "id": "cloudflare-cdn",
        "name": "Cloudflare CDN + DNS",
        "category": "cdn-dns",
        "summary": "免费 CDN + DNS 不限域名数量 + 免费 SSL + 免费 DDoS 防护，个人开发者最优解。",
        "quota": "CDN 流量不限；DNS 域名数不限；免费 SSL",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.cloudflare.com",
        "tips": "免费版国内访问速度一般（节点在境外），但稳定性好。",
        "tags": "cdn 域名 dns 免费 ssl 证书 cloudflare 加速",
        "reviewed": "2026-09",
    },
    {
        "id": "cloudflare-tunnel",
        "name": "Cloudflare Tunnel",
        "category": "cdn-dns",
        "summary": "内网穿透利器：把本地端口暴露到公网，连注册都不用（快速隧道）。",
        "quota": "免费",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/",
        "tips": "本项目自己的公网入口就是用它做的（不稳定在随机域名会变）。",
        "tags": "内网穿透 免费 隧道 域名 cloudflare tunnel 反代",
        "reviewed": "2026-09",
    },
    {
        "id": "lets-encrypt",
        "name": "Let's Encrypt",
        "category": "cdn-dns",
        "summary": "免费 SSL 证书，被所有主流浏览器信任，行业标准。",
        "quota": "无限免费证书",
        "requirements": ["免信用卡"],
        "china": "cn_ok",
        "expiry": "长期（90 天自动续期）",
        "url": "https://letsencrypt.org/zh-cn/",
        "tips": "用 certbot 或 acme.sh 自动续期；国内服务器也能用。",
        "tags": "ssl 证书 https 免费 域名 letsencrypt",
        "reviewed": "2026-09",
    },
    {
        "id": "freenom-alt",
        "name": "免费二级域名（多种选择）",
        "category": "cdn-dns",
        "summary": "做测试站点时够用的免费域名：eu.org、dedyn.io、js.org 等。",
        "quota": "免费二级域名",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://nic.eu.org",
        "tips": "免费域名申请通常要人工审核（等几天）；不适合正式项目。",
        "tags": "域名 免费 二级域名 dns eu.org",
        "reviewed": "2026-09",
    },

    # ══════════════════ CI/CD / 代码托管 ══════════════════
    {
        "id": "github-actions",
        "name": "GitHub Actions",
        "category": "cicd",
        "summary": "公开仓库 CI/CD 完全免费无限分钟；私有仓库每月 2000 分钟。",
        "quota": "公开仓库无限；私有仓库 2000 分钟/月",
        "requirements": ["需 GitHub 账号", "免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://github.com/features/actions",
        "tips": "本项目的整条 CI/CD 流水线就跑在这里。",
        "tags": "ci cd 持续集成 免费 流水线 github actions",
        "reviewed": "2026-09",
    },
    {
        "id": "gitee",
        "name": "Gitee（码云）",
        "category": "cicd",
        "summary": "国内代码托管，访问快，私有仓库和 CI 有免费额度。",
        "quota": "免费私有仓库 + 免费 CI 额度",
        "requirements": ["需实名"],
        "china": "cn_ok",
        "expiry": "长期",
        "url": "https://gitee.com",
        "tips": "国内网络友好；开源项目发布也可考虑作镜像仓库。",
        "tags": "代码托管 免费 git 国内 gitee 码云 ci",
        "reviewed": "2026-09",
    },
    {
        "id": "codeberg",
        "name": "Codeberg",
        "category": "cicd",
        "summary": "非营利组织运营的开源代码托管，无限仓库 + 自带 CI。",
        "quota": "无限公开/私有仓库",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://codeberg.org",
        "tips": "基于 Forgejo，无广告无追踪。",
        "tags": "代码托管 免费 git codeberg ci",
        "reviewed": "2026-09",
    },

    # ══════════════════ 监控 / 告警 / 日志 ══════════════════
    {
        "id": "uptimerobot",
        "name": "UptimeRobot",
        "category": "monitor",
        "summary": "免费网站可用性监控，每 5 分钟探测一次，挂了发邮件/短信。",
        "quota": "50 个监控项，5 分钟间隔",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://uptimerobot.com",
        "tips": "最轻量的「我的站还活着吗」方案。",
        "tags": "监控 告警 免费 可用性 网站 uptimerobot",
        "reviewed": "2026-09",
    },
    {
        "id": "sentry",
        "name": "Sentry",
        "category": "monitor",
        "summary": "错误追踪，免费额度够个人项目（每月 5000 个错误事件）。",
        "quota": "5000 错误事件/月，1 个用户",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://sentry.io",
        "tips": "接入 SDK 后能自动捕获异常堆栈，比自己写日志好用得多。",
        "tags": "监控 错误追踪 免费 异常 sentry 日志",
        "reviewed": "2026-09",
    },
    {
        "id": "grafana-cloud",
        "name": "Grafana Cloud 免费层",
        "category": "monitor",
        "summary": "托管版 Grafana + Prometheus + Loki，免费额度可长期使用。",
        "quota": "10k 指标序列 + 50GB 日志/月（免费层）",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://grafana.com/products/cloud/",
        "tips": "不想自建 Prometheus 时的省事选择；本项目选择自建（更能学到东西）。",
        "tags": "监控 指标 日志 免费 grafana prometheus loki",
        "reviewed": "2026-09",
    },
    {
        "id": "betterstack",
        "name": "Better Stack",
        "category": "monitor",
        "summary": "日志 + 可用性监控，免费层带 10 个监控项和日志额度。",
        "quota": "10 个监控 + 日志免费额度",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://betterstack.com",
        "tips": "界面友好，适合当 UptimeRobot 的替代。",
        "tags": "监控 日志 免费 可用性 betterstack",
        "reviewed": "2026-09",
    },

    # ══════════════════ 邮件发送 ══════════════════
    {
        "id": "resend",
        "name": "Resend",
        "category": "email",
        "summary": "开发者友好的邮件 API，每月 3000 封免费。",
        "quota": "3000 封/月，100 封/天",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://resend.com",
        "tips": "要发到自己的域名需要配 DNS 记录（SPF/DKIM）。",
        "tags": "邮件 发送 免费 smtp 邮件api resend",
        "reviewed": "2026-09",
    },
    {
        "id": "sendgrid",
        "name": "SendGrid",
        "category": "email",
        "summary": "老牌邮件服务，免费每天 100 封。",
        "quota": "100 封/天",
        "requirements": ["需实名审核"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://sendgrid.com",
        "tips": "注册审核较严，可能需要说明用途。",
        "tags": "邮件 发送 免费 smtp sendgrid",
        "reviewed": "2026-09",
    },
    {
        "id": "brevo",
        "name": "Brevo（原 Sendinblue）",
        "category": "email",
        "summary": "每天 300 封免费邮件额度，是免费额度里较大的。",
        "quota": "300 封/天",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.brevo.com",
        "tips": "同时带营销邮件和 SMS 能力。",
        "tags": "邮件 发送 免费 smtp brevo sendinblue",
        "reviewed": "2026-09",
    },

    # ══════════════════ 登录 / 认证 ══════════════════
    {
        "id": "clerk",
        "name": "Clerk",
        "category": "auth",
        "summary": "开箱即用的登录组件，5 万月活用户免费。",
        "quota": "5 万 MAU",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://clerk.com",
        "tips": "前端几行代码就能加登录/注册/第三方登录。",
        "tags": "认证 登录 免费 用户管理 auth clerk",
        "reviewed": "2026-09",
    },
    {
        "id": "supabase-auth",
        "name": "Supabase Auth",
        "category": "auth",
        "summary": "和 Supabase 数据库打包的认证服务，免费额度大。",
        "quota": "随 Supabase 免费项目，5 万 MAU 级别",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://supabase.com/auth",
        "tips": "已经用 Supabase 的话直接用它，不用再引入新服务。",
        "tags": "认证 登录 免费 supabase auth 用户",
        "reviewed": "2026-09",
    },

    # ══════════════════ 开发工具 / 其他 ══════════════════
    {
        "id": "cloudflare-turnstile",
        "name": "Cloudflare Turnstile",
        "category": "devtool",
        "summary": "免费验证码替代品，无感验证，比 reCAPTCHA 更干净。",
        "quota": "免费无限",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.cloudflare.com/products/turnstile/",
        "tips": "国内用户也能正常加载（比 reCAPTCHA 强）。",
        "tags": "验证码 免费 安全 turnstile 人机验证",
        "reviewed": "2026-09",
    },
    {
        "id": "github-codespaces",
        "name": "GitHub Codespaces",
        "category": "devtool",
        "summary": "云端 VS Code，每月 120 核时免费，配好环境随时开工。",
        "quota": "120 核时/月 + 15GB 存储",
        "requirements": ["需 GitHub 账号", "免信用卡"],
        "china": "cn_partial",
        "expiry": "每月重置",
        "url": "https://github.com/features/codespaces",
        "tips": "适合在没有开发环境的设备上写代码；用 SSH 连进去也行。",
        "tags": "开发工具 免费 云端 ide vscode codespaces",
        "reviewed": "2026-09",
    },
    {
        "id": "cloudflare-email-routing",
        "name": "Cloudflare Email Routing",
        "category": "devtool",
        "summary": "用自己的域名收发邮件，免费转发到你的常用邮箱。",
        "quota": "免费无限转发",
        "requirements": ["需自己的域名", "免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://developers.cloudflare.com/email-routing/",
        "tips": "做「admin@你的域名」这种专业邮箱地址最省钱的方式。",
        "tags": "邮箱 域名 免费 转发 email routing",
        "reviewed": "2026-09",
    },
    {
        "id": "jsdelivr",
        "name": "jsDelivr",
        "category": "devtool",
        "summary": "免费 CDN，直接从 npm / GitHub 提供静态资源，国内有节点。",
        "quota": "免费无限",
        "requirements": ["免信用卡"],
        "china": "cn_ok",
        "expiry": "长期",
        "url": "https://www.jsdelivr.com",
        "tips": "免费 CDN 里国内访问最稳的之一，适合放前端库文件。",
        "tags": "cdn 免费 jsdelivr 静态资源 前端",
        "reviewed": "2026-09",
    },

    # ══════════════════ 学生专属福利（学生党最该先拿的） ══════════════════
    {
        "id": "github-student-pack",
        "name": "GitHub 学生开发者包",
        "category": "student",
        "summary": "一个学生身份，换取几十家服务商的免费额度 —— 学生党能拿到的最大一份羊毛，价值上千美元。",
        "quota": "含 DigitalOcean 200 美元额度、Namecheap 免费域名 1 年、JetBrains 全家桶、域名/云主机/CI/监控等几十项",
        "requirements": ["需学生身份验证", "免信用卡"],
        "china": "cn_partial",
        "expiry": "在校期间",
        "url": "https://education.github.com/pack",
        "tips": "用学校邮箱 + 学生证申请，一般几天到两周批下来。国内高校学生可以申请（需要能证明在读）。这是本清单里性价比最高的一条。",
        "tags": "学生 免费 教育 github 学生包 羊毛 digitalocean 域名 jetbrains",
        "reviewed": "2026-09",
    },
    {
        "id": "jetbrains-student",
        "name": "JetBrains 学生授权",
        "category": "student",
        "summary": "IntelliJ IDEA / PyCharm / WebStorm 等全家桶专业版免费，在校期间一直续。",
        "quota": "全部 IDE 专业版免费（原价每年数千元）",
        "requirements": ["需学生身份验证", "免信用卡"],
        "china": "cn_ok",
        "expiry": "在校期间（每年续期）",
        "url": "https://www.jetbrains.com/community/education/#students",
        "tips": "用学校邮箱或学信网证明申请，通常几分钟到几小时就批。比社区版多出数据库工具、远程开发等能力。",
        "tags": "学生 免费 ide jetbrains idea pycharm webstorm 教育",
        "reviewed": "2026-09",
    },
    {
        "id": "azure-for-students",
        "name": "Azure for Students",
        "category": "student",
        "summary": "微软给学生的 100 美元云额度，一年内用，且不需要信用卡。",
        "quota": "100 美元额度 + 部分免费服务（12 个月）",
        "requirements": ["需学生身份", "免信用卡"],
        "china": "cn_partial",
        "expiry": "1 年",
        "url": "https://azure.microsoft.com/zh-cn/free/students/",
        "tips": "最大优点是不用绑卡；额度用完就停，不会自动扣费。",
        "tags": "学生 免费 云服务器 azure 微软 额度",
        "reviewed": "2026-09",
    },
    {
        "id": "ms-office-education",
        "name": "微软 Office 教育版",
        "category": "student",
        "summary": "用学校邮箱通常能免费拿到 Office 365 全套（网页版 + 桌面版视学校授权）。",
        "quota": "免费（视学校订阅而定）",
        "requirements": ["需学校邮箱", "免信用卡"],
        "china": "cn_partial",
        "expiry": "在校期间",
        "url": "https://www.microsoft.com/zh-cn/education/products/office",
        "tips": "输入学校邮箱试一下就知道；很多学校已购买订阅，学生直接白拿。",
        "tags": "学生 免费 office 微软 word excel 教育",
        "reviewed": "2026-09",
    },
    {
        "id": "aliyun-campus",
        "name": "阿里云高校计划 / 腾讯云校园",
        "category": "student",
        "summary": "国内云厂商给在校生的专属优惠：云服务器、数据库、AI 算力都有学生价甚至免费额度。",
        "quota": "学生认证后可领免费试用额度与专属折扣（以活动页为准）",
        "requirements": ["需学生身份（学信网）", "免信用卡"],
        "china": "cn_ok",
        "expiry": "以活动页为准",
        "url": "https://university.aliyun.com/",
        "tips": "国内做实验最省事的路子：实名 + 学生认证后常有几百元额度或低价年付。腾讯云对应「校园」活动，两家都看看。",
        "tags": "学生 免费 云服务器 阿里云 腾讯云 高校 校园",
        "reviewed": "2026-09",
    },

    # ══════════════════ 更多国内 AI 平台 ══════════════════
    {
        "id": "volcengine-doubao",
        "name": "火山引擎豆包（字节）",
        "category": "ai-api",
        "summary": "字节跳动的豆包大模型，新用户有免费 tokens 额度，价格在国内平台里偏低。",
        "quota": "新用户免费额度（以控制台为准）",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "以活动为准",
        "url": "https://www.volcengine.com/product/doubao",
        "tips": "开通「火山方舟」后领取；豆包在中文创作和长文场景表现不错。",
        "tags": "ai 大模型 llm api 豆包 doubao 字节 火山引擎 免费",
        "reviewed": "2026-09",
    },
    {
        "id": "baidu-qianfan",
        "name": "百度智能云千帆",
        "category": "ai-api",
        "summary": "文心一言系列模型的 API 平台，新用户有免费额度。",
        "quota": "新用户免费额度（以控制台为准）",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "以活动为准",
        "url": "https://qianfan.cloud.baidu.com/",
        "tips": "顺带能用百度的 OCR / 语音 / 翻译等免费额度（见「其他免费 API」分类）。",
        "tags": "ai 大模型 llm api 文心 千帆 百度 免费",
        "reviewed": "2026-09",
    },
    {
        "id": "modelscope",
        "name": "ModelScope 魔搭（阿里）",
        "category": "ai-api",
        "summary": "阿里开源的模型社区，提供在线推理和 API 调用，有每日免费额度。",
        "quota": "每日免费调用额度（以页面为准）",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "长期",
        "url": "https://modelscope.cn/",
        "tips": "好处是模型可以直接在线试跑，不用自己部署。适合快速比较不同开源模型。",
        "tags": "ai 大模型 llm api 魔搭 modelscope 阿里 免费",
        "reviewed": "2026-09",
    },
    {
        "id": "stepfun",
        "name": "阶跃星辰 StepFun",
        "category": "ai-api",
        "summary": "国产多模态大模型平台，新用户有赠送额度。",
        "quota": "新用户赠送额度（以官网为准）",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "以官网为准",
        "url": "https://platform.stepfun.com/",
        "tips": "多模态（图像理解）能力较强，适合做需要看图的任务。",
        "tags": "ai 大模型 llm api 阶跃星辰 stepfun 多模态 免费",
        "reviewed": "2026-09",
    },
    {
        "id": "lingyiwanwu",
        "name": "零一万物 Yi",
        "category": "ai-api",
        "summary": "李开复团队的 Yi 系列模型平台，新用户有免费额度。",
        "quota": "新用户赠送额度（以官网为准）",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "以官网为准",
        "url": "https://platform.lingyiwanwu.com/",
        "tips": "开源模型权重也能下载自己部署，算力和 API 两种用法都行。",
        "tags": "ai 大模型 llm api 零一万物 yi 开源 免费",
        "reviewed": "2026-09",
    },
    {
        "id": "cerebras",
        "name": "Cerebras",
        "category": "ai-api",
        "summary": "推理速度极快的免费 API，**不需要绑卡**，适合做实时对话。",
        "quota": "免费层（有每分钟/每日速率限制）",
        "requirements": ["免信用卡"],
        "china": "cn_no",
        "expiry": "长期",
        "url": "https://cloud.cerebras.ai/",
        "tips": "模型含 llama / qwen 等开源模型；超限返回 429。国内访问需自行解决网络。",
        "tags": "ai 大模型 llm api cerebras 免费 快速 推理",
        "reviewed": "2026-09",
    },
    {
        "id": "sambanova",
        "name": "SambaNova",
        "category": "ai-api",
        "summary": "注册赠送积分，可换算成相当可观的 tokens 用量。",
        "quota": "注册赠送 5 美元积分（约数千万 tokens，以官网为准）",
        "requirements": ["免信用卡"],
        "china": "cn_no",
        "expiry": "约 30 天",
        "url": "https://cloud.sambanova.ai/",
        "tips": "不绑卡也能调 DeepSeek / Llama 系列；额度有有效期，别攒着不用。",
        "tags": "ai 大模型 llm api sambanova 免费 tokens",
        "reviewed": "2026-09",
    },
    {
        "id": "mistral-free",
        "name": "Mistral AI（免费层）",
        "category": "ai-api",
        "summary": "法国开源模型厂商，API 有免费层（La Plateforme）。",
        "quota": "免费层（有速率限制，以官网为准）",
        "requirements": ["免信用卡"],
        "china": "cn_no",
        "expiry": "长期",
        "url": "https://console.mistral.ai/",
        "tips": "模型体积小、速度快、可自托管；欧洲合规场景常被选用。",
        "tags": "ai 大模型 llm api mistral 免费 开源",
        "reviewed": "2026-09",
    },
    {
        "id": "cloudflare-workers-ai",
        "name": "Cloudflare Workers AI",
        "category": "ai-api",
        "summary": "在 Cloudflare 边缘网络跑开源模型，每天有免费额度，和 Workers 天然集成。",
        "quota": "每天免费推理额度（以官网为准）",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://developers.cloudflare.com/workers-ai/",
        "tips": "适合做轻量的翻译/摘要/图像识别，延迟低；重任务不适合。",
        "tags": "ai 大模型 llm api cloudflare 边缘 免费 workers",
        "reviewed": "2026-09",
    },

    # ══════════════════ 更多免费云 / 托管 ══════════════════
    {
        "id": "flyio",
        "name": "Fly.io",
        "category": "hosting",
        "summary": "把容器部署到全球边缘节点，有免费额度（按用量抵扣）。",
        "quota": "免费额度（视套餐调整，以官网为准）",
        "requirements": ["需信用卡"],
        "china": "cn_no",
        "expiry": "长期（政策有变动）",
        "url": "https://fly.io/",
        "tips": "免费政策浮动过几次，绑卡前先看清楚当前方案；适合部署长驻后端。",
        "tags": "网站托管 部署 免费 容器 fly.io 边缘",
        "reviewed": "2026-09",
    },
    {
        "id": "koyeb",
        "name": "Koyeb",
        "category": "hosting",
        "summary": "免费档可以跑一个常驻小服务（比 Render 更不容易休眠）。",
        "quota": "免费实例（以官网为准）",
        "requirements": ["免信用卡"],
        "china": "cn_no",
        "expiry": "长期",
        "url": "https://www.koyeb.com/",
        "tips": "免费实例规格很小，适合小 API / bot；数据库另配。",
        "tags": "网站托管 部署 免费 容器 koyeb paas",
        "reviewed": "2026-09",
    },
    {
        "id": "deno-deploy",
        "name": "Deno Deploy",
        "category": "hosting",
        "summary": "边缘 Serverless，免费额度够跑几个小接口，部署只需一条命令。",
        "quota": "免费层（每日请求额度）",
        "requirements": ["免信用卡"],
        "china": "cn_no",
        "expiry": "长期",
        "url": "https://deno.com/deploy",
        "tips": "TypeScript 原生支持，写 API / webhook 最省事。",
        "tags": "网站托管 部署 免费 serverless deno 边缘 typescript",
        "reviewed": "2026-09",
    },
    {
        "id": "tencent-cloudbase",
        "name": "腾讯云开发 CloudBase",
        "category": "hosting",
        "summary": "国内的一体化后端服务：静态托管 + 云函数 + 数据库，有免费额度。",
        "quota": "免费额度（以官网为准）",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "长期免费额度",
        "url": "https://cloudbase.net/",
        "tips": "国内做小程序/小网站最省事的选择之一；国内访问速度好。",
        "tags": "网站托管 部署 免费 serverless 云开发 腾讯云 国内",
        "reviewed": "2026-09",
    },
    {
        "id": "aliyun-fc",
        "name": "阿里云函数计算 FC",
        "category": "hosting",
        "summary": "国内 Serverless 函数，每月有免费调用额度，适合定时任务和小接口。",
        "quota": "每月免费额度（调用次数 + 资源用量）",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "长期免费额度",
        "url": "https://www.aliyun.com/product/fc",
        "tips": "国内定时任务（爬虫/巡检）比买服务器划算得多；注意免费额度用量监控。",
        "tags": "serverless 函数 免费 阿里云 fc 国内 定时任务",
        "reviewed": "2026-09",
    },
    {
        "id": "surge",
        "name": "Surge.sh",
        "category": "hosting",
        "summary": "命令行一条命令发布静态站，免费不限站点数，最轻量的静态托管。",
        "quota": "免费：不限站点、自定义域名、SSL",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://surge.sh/",
        "tips": "没有 CI 集成，适合手工发布的小页面；国内访问一般。",
        "tags": "静态托管 部署 免费 surge 前端 ssl",
        "reviewed": "2026-09",
    },

    # ══════════════════ 其他免费 API（高价值） ══════════════════
    {
        "id": "deepl-free",
        "name": "DeepL 翻译 API",
        "category": "api-other",
        "summary": "翻译质量公认最好的 API，免费层每月 50 万字符。",
        "quota": "免费 50 万字符/月",
        "requirements": ["需信用卡验证（免费版可能不扣费）"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.deepl.com/pro-api",
        "tips": "免费版（Free）额度不小；中英互译质量明显好于通用翻译。",
        "tags": "翻译 api 免费 deepl 中英 文本",
        "reviewed": "2026-09",
    },
    {
        "id": "baidu-ocr",
        "name": "百度智能云 OCR",
        "category": "api-other",
        "summary": "文字识别 API，新用户有免费调用额度，中文识别效果好。",
        "quota": "新用户免费额度（各接口独立计数）",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "以控制台为准",
        "url": "https://cloud.baidu.com/product/ocr.html",
        "tips": "身份证/银行卡/通用文字等接口额度分开算，够做小工具。",
        "tags": "ocr 文字识别 api 免费 百度 中文 图像",
        "reviewed": "2026-09",
    },
    {
        "id": "amap-free",
        "name": "高德地图开放平台",
        "category": "api-other",
        "summary": "国内地图 API 首选，个人开发者有较高免费调用额度。",
        "quota": "个人开发者每日免费调用量（以官网为准）",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "长期",
        "url": "https://lbs.amap.com/",
        "tips": "定位/路径规划/POI 搜索都覆盖；国内做地图应用用它最省事。",
        "tags": "地图 api 免费 高德 定位 导航 国内",
        "reviewed": "2026-09",
    },
    {
        "id": "mapbox-free",
        "name": "Mapbox",
        "category": "api-other",
        "summary": "海外地图服务，每月有免费请求额度，可视化效果漂亮。",
        "quota": "每月免费请求额度（以官网为准）",
        "requirements": ["需信用卡（部分档位）"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.mapbox.com/",
        "tips": "样式定制能力强；国内访问速度一般，国内项目优先考虑高德。",
        "tags": "地图 api 免费 mapbox 可视化 定位",
        "reviewed": "2026-09",
    },
    {
        "id": "twilio-trial",
        "name": "Twilio（短信/语音）",
        "category": "api-other",
        "summary": "发短信的行业标准服务，试用账号有赠送额度。",
        "quota": "试用额度（含短信/语音）",
        "requirements": ["需信用卡（试用也要验证）"],
        "china": "cn_no",
        "expiry": "试用期",
        "url": "https://www.twilio.com/try-twilio",
        "tips": "国内号码收短信需要在 Twilio 后台开通对应国家权限，且中国区短信政策严格。",
        "tags": "短信 语音 api 免费 twilio 通知",
        "reviewed": "2026-09",
    },
    {
        "id": "zoho-mail",
        "name": "Zoho Mail 免费企业邮箱",
        "category": "email",
        "summary": "用自己的域名开企业邮箱，免费版够个人用（收信 + 少量发信）。",
        "quota": "免费版：1 个用户 5GB，支持自定义域名",
        "requirements": ["需自有域名", "免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.zoho.com/mail/",
        "tips": "比 Cloudflare Email Routing（只转发）多一个完整邮箱本体；配 DNS 记录即可。",
        "tags": "邮箱 免费 企业邮箱 域名 zoho 收发信",
        "reviewed": "2026-09",
    },
    {
        "id": "appwrite-cloud",
        "name": "Appwrite Cloud",
        "category": "auth",
        "summary": "开源版 Firebase，免费档含认证 + 数据库 + 存储 + 云函数。",
        "quota": "免费档（有项目数和流量限制）",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://appwrite.io/",
        "tips": "和 Supabase 是同类竞品，也可以自托管到自己的服务器上。",
        "tags": "认证 登录 免费 后端 baas appwrite 数据库",
        "reviewed": "2026-09",
    },
]


# ══════════════════ 定向补充（按用户需求追加，保持在上面的列表之后） ══════════════════
_EXTRA_ENTRIES: list[dict] = [
    {
        "id": "meilisearch-cloud",
        "name": "Meilisearch Cloud / Algolia",
        "category": "api-other",
        "summary": "给网站加搜索功能的两条主流路线，都有免费档。",
        "quota": "Meilisearch Cloud 免费试用；Algolia 免费档每月一定量请求",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期（Algolia）/ 试用（Meilisearch）",
        "url": "https://www.algolia.com/",
        "tips": "小项目建议直接自托管 Meilisearch（开源免费）；数据量小的时候 Algolia 免费档够用。",
        "tags": "搜索 api 免费 algolia meilisearch 全文检索",
        "reviewed": "2026-09",
    },
    {
        "id": "duckdns",
        "name": "DuckDNS / FreeDNS 动态域名",
        "category": "cdn-dns",
        "summary": "免费动态域名（DDNS）：家里/服务器的动态 IP 也能有个固定域名。",
        "quota": "免费二级域名（DuckDNS 可建 5 个）",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.duckdns.org/",
        "tips": "配合 CNAME 或者 API 定时更新 IP，适合自建服务用；别拿它做正式业务的域名。",
        "tags": "域名 dns 免费 ddns 动态域名 duckdns 解析",
        "reviewed": "2026-09",
    },
]

ENTRIES = ENTRIES + _EXTRA_ENTRIES


def as_list() -> list[dict]:
    """返回全部精选条目（浅拷贝，避免调用方误改模块常量）。"""
    return [dict(e) for e in ENTRIES]


def category_name(key: str) -> str:
    for k, name in CATEGORIES:
        if k == key:
            return name
    return key
