"""数据层适配：同一套业务代码，既能跑 SQLite 也能跑 PostgreSQL。

为什么要做这个（而不是直接用 PG）：
- **本地开发和单测不该依赖数据库服务** —— 跑 `pytest` 就得先起一个 PG，太重
- 部署到集群时换成 PG，才能解除「单文件 + RWO 卷」对多副本的限制

所以规则是：**没配 `RADAR_DB_URL` 就用 SQLite，配了就按 URL 走**。
业务代码只调用 `connect()`，完全不知道底层是谁。

两种库的差异（都在这里消化掉，不泄漏到上层）：
| 差异 | SQLite | PostgreSQL |
|---|---|---|
| 占位符 | `?` | `%s` |
| 自增主键 | `AUTOINCREMENT` | `GENERATED BY DEFAULT AS IDENTITY` |
| 行对象 | `sqlite3.Row` | `dict_row` |
| 并发写 | 单写者（WAL） | 真正的并发 |
| 开关参数 | `PRAGMA ...` | 无 |

⚠️ 迁移时踩过的点：SQLite 里 `?` 出现在字符串字面量里也会被替换，
所以替换占位符必须**跳过引号内的内容**（见 `_to_pg_sql`）。
"""

from __future__ import annotations

import os
import re
import sqlite3
from pathlib import Path
from typing import Any, Iterable, Sequence

DB_URL = os.getenv("RADAR_DB_URL", "").strip()

# ── 表结构：两种方言各写一份（DDL 差异无法用参数化抹平）──────────────
_COMMON_TABLES = """
CREATE TABLE IF NOT EXISTS snapshots (
    id          {pk},
    fetched_at  TEXT    NOT NULL,
    entry_count INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS entries (
    snapshot_id INTEGER NOT NULL,
    entry_key   TEXT    NOT NULL,
    category    TEXT    NOT NULL,
    parent      TEXT,
    name        TEXT    NOT NULL,
    url         TEXT,
    description TEXT    NOT NULL DEFAULT '',
    fingerprint TEXT    NOT NULL,
    PRIMARY KEY (snapshot_id, entry_key)
);

CREATE TABLE IF NOT EXISTS changes (
    id              {pk},
    detected_at     TEXT    NOT NULL,
    change_type     TEXT    NOT NULL,
    entry_key       TEXT    NOT NULL,
    category        TEXT    NOT NULL,
    name            TEXT    NOT NULL,
    url             TEXT,
    old_description TEXT,
    new_description TEXT
);

CREATE INDEX IF NOT EXISTS idx_changes_detected_at ON changes(detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_changes_entry_key ON changes(entry_key);
CREATE INDEX IF NOT EXISTS idx_changes_type ON changes(change_type);

CREATE TABLE IF NOT EXISTS mine (
    entry_id      TEXT PRIMARY KEY,
    status        TEXT NOT NULL DEFAULT 'interested',
    registered_at TEXT,
    expires_at    TEXT,
    note          TEXT,
    updated_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_mine_expires_at ON mine(expires_at);
CREATE INDEX IF NOT EXISTS idx_mine_status ON mine(status);

CREATE TABLE IF NOT EXISTS link_checks (
    id          {pk},
    entry_id    TEXT    NOT NULL,
    checked_at  TEXT    NOT NULL,
    ok          INTEGER NOT NULL,
    status_code INTEGER,
    error       TEXT
);

CREATE INDEX IF NOT EXISTS idx_link_checks_entry ON link_checks(entry_id, id DESC);

CREATE TABLE IF NOT EXISTS seen_entries (
    entry_id   TEXT PRIMARY KEY,
    first_seen TEXT NOT NULL,
    last_seen  TEXT NOT NULL
);
"""

SQLITE_PK = "INTEGER PRIMARY KEY AUTOINCREMENT"
PG_PK = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"

SQLITE_SCHEMA = _COMMON_TABLES.format(pk=SQLITE_PK)
PG_SCHEMA = _COMMON_TABLES.format(pk=PG_PK)


def using_postgres() -> bool:
    return DB_URL.startswith(("postgres://", "postgresql://"))


# ── SQL 方言转换 ───────────────────────────────────────────────────────
_QUOTED = re.compile(r"'(?:[^']|'')*'")


def _to_pg_sql(sql: str) -> str:
    """把 `?` 占位符换成 `%s`，但**引号内的问号必须原样保留**。

    引号里的 `?` 是**数据**不是占位符，比如：
        SELECT * FROM t WHERE note = '还有几天?'
    原样替换会把它变成 `%s`，psycopg 又会把 `%` 当格式符 → SQL 直接报错。
    （这类 bug 在带中文文案的查询里特别容易埋进去，所以单独写了测试。）
    """
    parts: list[str] = []
    last = 0
    for m in _QUOTED.finditer(sql):
        parts.append(sql[last:m.start()].replace("?", "%s"))
        parts.append(m.group(0))  # 引号内原样保留
        last = m.end()
    parts.append(sql[last:].replace("?", "%s"))
    return "".join(parts)


class _Cursor:
    """统一 cursor 的最小接口：只有 fetchone / fetchall / rowcount。"""

    def __init__(self, cur, is_pg: bool):
        self._cur = cur
        self._is_pg = is_pg

    def fetchone(self):
        row = self._cur.fetchone()
        return row

    def fetchall(self):
        return self._cur.fetchall()

    @property
    def rowcount(self) -> int:
        return self._cur.rowcount

    def __iter__(self):
        return iter(self._cur)


class Connection:
    """业务代码只认这个对象。"""

    def __init__(self, raw: Any, is_pg: bool):
        self._raw = raw
        self._is_pg = is_pg

    def execute(self, sql: str, params: Sequence[Any] | None = None) -> _Cursor:
        cur = self._raw.cursor()
        if params is None:
            cur.execute(sql if not self._is_pg else _to_pg_sql(sql))
        else:
            cur.execute(sql if not self._is_pg else _to_pg_sql(sql), tuple(params))
        return _Cursor(cur, self._is_pg)

    def executemany(self, sql: str, seq: Iterable[Sequence[Any]]) -> _Cursor:
        cur = self._raw.cursor()
        cur.executemany(sql if not self._is_pg else _to_pg_sql(sql), [tuple(p) for p in seq])
        return _Cursor(cur, self._is_pg)

    def commit(self) -> None:
        self._raw.commit()

    def close(self) -> None:
        self._raw.close()


def connect_sqlite(path: Path | str) -> Connection:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    raw = sqlite3.connect(p)
    raw.row_factory = sqlite3.Row
    raw.execute("PRAGMA journal_mode=WAL")
    raw.execute("PRAGMA foreign_keys=ON")
    raw.executescript(SQLITE_SCHEMA)
    return Connection(raw, is_pg=False)


def connect_postgres(url: str) -> Connection:
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError(
            "配了 RADAR_DB_URL 但没装 psycopg —— 请 pip install 'psycopg[binary]'"
        ) from exc

    raw = psycopg.connect(url, row_factory=dict_row, autocommit=False)
    for stmt in PG_SCHEMA.split(";"):
        s = stmt.strip()
        if s:
            raw.execute(s)
    raw.commit()
    # 兼容老代码里的 INTEGER 布尔判断（SQLite 存 0/1，PG 里也是 INTEGER，无需转换）
    return Connection(raw, is_pg=True)
