"""人工整理的中文精选免费资源。

为什么单独维护这份数据（而不是只抓 free-for-dev）：
  1. 国内平台 free-for-dev 一条都没有 —— 智谱、百炼、讯飞、腾讯混元、硅基流动
     这些国内免费额度对学生党最实用，但那份英文清单完全没收录。
  2. free-for-dev 只有英文描述，且需要自己 Ctrl+F 翻；这里每条都写了
     「免费额度 / 要求 / 国内能不能用 / 有什么坑」四个中国用户最关心的字段。
  3. 人工核实过的条目可以标注可信度，避免「注册完发现要绑卡」这种浪费。

数据整理时间：2026-09。免费政策随时会变，请以官网为准。
每条都带 `reviewed` 字段记录核对日期。
"""

from __future__ import annotations

# ── 分类（中文名 + 排序权重，权重小的排前面）────────────────────────────
CATEGORIES: list[tuple[str, str]] = [
    ("ai-api", "AI 大模型 API"),
    ("ai-compute", "AI 算力 / GPU"),
    ("cloud", "云服务器 / 免费额度"),
    ("hosting", "网站托管 / 部署"),
    ("database", "数据库"),
    ("storage", "对象存储 / 图床"),
    ("cdn-dns", "域名 / DNS / CDN"),
    ("cicd", "CI/CD / 代码托管"),
    ("monitor", "监控 / 告警 / 日志"),
    ("email", "邮件发送"),
    ("auth", "登录 / 认证"),
    ("devtool", "开发工具 / 其他"),
]

# ── 标签（用于筛选，中文）────────────────────────────────────────────────
# need_card   需信用卡    need_id   需实名认证    no_card   免信用卡
# cn_ok       国内直连    cn_partial 部分可用     cn_no     需梯子
# permanent   长期免费    limited   限时赠送

ENTRIES: list[dict] = [
    # ══════════════════ AI 大模型 API（用户最关心）══════════════════
    {
        "id": "zhipu",
        "name": "智谱 AI（GLM）",
        "category": "ai-api",
        "summary": "国内大模型第一梯队，注册即送 2000 万 tokens 体验包，编程能力强的 GLM 系列。",
        "quota": "新用户 2000 万 tokens（含 1200 万 glm-4.5-air + 600 万 glm-4.6v + 200 万通用）",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "3 个月有效",
        "url": "https://www.bigmodel.cn",
        "tips": "注册后在「财务 → 资源包」查看剩余额度；优先消耗快过期的。",
        "tags": "ai 大模型 llm api 免费 tokens 国产 glm 编程",
        "reviewed": "2026-09",
    },
    {
        "id": "aliyun-bailian",
        "name": "阿里云百炼（DashScope）",
        "category": "ai-api",
        "summary": "模型最全的国内平台，包含 qwen、deepseek 系列，新用户每个模型 100 万 tokens 免费额度。",
        "quota": "各模型 100 万 tokens，有效期 90 天",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "90 天",
        "url": "https://bailian.console.aliyun.com",
        "tips": "控制台「模型用量 → 免费额度」可看总额度与到期时间；务必打开「用完即停」避免超额扣费。",
        "tags": "ai 大模型 llm api qwen 通义 deepseek 免费 tokens 阿里云",
        "reviewed": "2026-09",
    },
    {
        "id": "xfyun-spark",
        "name": "讯飞星火",
        "category": "ai-api",
        "summary": "注册直接领 500 万 tokens，中文问答和数理逻辑表现好。",
        "quota": "500 万 tokens",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "以官网为准",
        "url": "https://www.xfyun.cn",
        "tips": "首页「星火大模型」入口领取。",
        "tags": "ai 大模型 llm api 星火 spark 免费 tokens 科大讯飞",
        "reviewed": "2026-09",
    },
    {
        "id": "tencent-hunyuan",
        "name": "腾讯云混元",
        "category": "ai-api",
        "summary": "实名后领 100 万 tokens 混元资源包，有效期长达 1 年（国内少见的长有效期）。",
        "quota": "混元大模型 100 万 tokens + 混元 embedding 100 万 tokens",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "1 年",
        "url": "https://console.cloud.tencent.com",
        "tips": "控制台控制台「资源包管理」查看；适合长期慢速使用。",
        "tags": "ai 大模型 llm api 混元 hunyuan 免费 tokens 腾讯云",
        "reviewed": "2026-09",
    },
    {
        "id": "moonshot-kimi",
        "name": "月之暗面 Kimi",
        "category": "ai-api",
        "summary": "长文本处理是业界标杆，注册完成个人认证送 15 元代金券。",
        "quota": "15 元赠送金额",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "约 3 个月",
        "url": "https://platform.moonshot.cn",
        "tips": "右上角「用户中心 → 组织认证」完成个人认证后自动到账。",
        "tags": "ai 大模型 llm api kimi 月之暗面 moonshot 免费 长文本",
        "reviewed": "2026-09",
    },
    {
        "id": "minimax",
        "name": "MiniMax",
        "category": "ai-api",
        "summary": "多模态能力强（文本/语音/视频/图像），实名后送 15 元代金券。",
        "quota": "15 元代金券",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "约 2 个月",
        "url": "https://platform.minimaxi.com",
        "tips": "完成个人实名认证后自动发放。",
        "tags": "ai 大模型 llm api minimax 语音 多模态 免费",
        "reviewed": "2026-09",
    },
    {
        "id": "siliconflow",
        "name": "硅基流动 SiliconFlow",
        "category": "ai-api",
        "summary": "一个 API 调全网主流开源模型（DeepSeek / Qwen / GLM / Kimi），实名送 16 元通用券。",
        "quota": "16 元平台通用代金券",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "180 天",
        "url": "https://cloud.siliconflow.cn",
        "tips": "首次实名认证后领取；适合横向对比不同模型效果。",
        "tags": "ai 大模型 llm api 硅基流动 siliconflow 免费 聚合",
        "reviewed": "2026-09",
    },
    {
        "id": "scnet",
        "name": "超算互联网",
        "category": "ai-api",
        "summary": "国家超算平台，新人送 100 万 tokens。",
        "quota": "100 万 tokens",
        "requirements": ["需实名", "免信用卡"],
        "china": "cn_ok",
        "expiry": "1 个月",
        "url": "https://www.scnet.cn",
        "tips": "首次登录领取；模型选择较少。",
        "tags": "ai 大模型 llm api 超算 免费 tokens",
        "reviewed": "2026-09",
    },
    {
        "id": "google-gemini-free",
        "name": "Google Gemini API（免费层）",
        "category": "ai-api",
        "summary": "海外最实用的免费大模型 API，有长期免费层（不是赠送额度，是持续免费）。",
        "quota": "免费层：每分钟 15 次请求 / 每天 1500 次（Gemini Flash 系列）",
        "requirements": ["需谷歌账号", "免信用卡"],
        "china": "cn_no",
        "expiry": "长期免费",
        "url": "https://ai.google.dev",
        "tips": "国内需自行解决网络；免费层数据可能被用于产品改进，别传敏感内容。",
        "tags": "ai 大模型 llm api gemini google 免费 免费层",
        "reviewed": "2026-09",
    },
    {
        "id": "openrouter",
        "name": "OpenRouter",
        "category": "ai-api",
        "summary": "全球最大的模型聚合网关，里面有 20+ 个完全免费的模型，一个 key 全都能调。",
        "quota": "约 28 个模型的免费额度（含 MiniMax、Step 等）",
        "requirements": ["免信用卡"],
        "china": "cn_no",
        "expiry": "长期（以平台为准）",
        "url": "https://openrouter.ai",
        "tips": "站内搜 'free' 可筛出所有免费模型；免费模型有速率限制。",
        "tags": "ai 大模型 llm api openrouter 聚合 免费模型",
        "reviewed": "2026-09",
    },
    {
        "id": "github-models",
        "name": "GitHub Models",
        "category": "ai-api",
        "summary": "用你已有的 GitHub 账号直接调 GPT-5 / GPT-4o 等模型，不用绑卡、不用另外注册。",
        "quota": "免费额度（按模型有速率限制）",
        "requirements": ["需 GitHub 账号", "免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://github.com/marketplace/models",
        "tips": "用 GitHub Token 直接调，是对国内用户最省事的海外模型入口之一。",
        "tags": "ai 大模型 llm api github gpt 免费 免绑卡",
        "reviewed": "2026-09",
    },
    {
        "id": "groq",
        "name": "Groq",
        "category": "ai-api",
        "summary": "推理速度极快的免费 API，不需要绑卡，适合做实时应用。",
        "quota": "免费层（有每分钟/每天速率限制）",
        "requirements": ["免信用卡"],
        "china": "cn_no",
        "expiry": "长期",
        "url": "https://console.groq.com",
        "tips": "超限会返回 429；模型含 llama、qwen 等开源模型。",
        "tags": "ai 大模型 llm api groq 免费 快速 推理",
        "reviewed": "2026-09",
    },
    {
        "id": "huggingface-inference",
        "name": "Hugging Face Inference API",
        "category": "ai-api",
        "summary": "几千个开源模型的免费推理额度，做实验最方便。",
        "quota": "每月一定量的免费调用",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://huggingface.co/inference-api",
        "tips": "部分模型需要排队；国内访问速度一般。",
        "tags": "ai 大模型 llm api huggingface 免费 开源模型",
        "reviewed": "2026-09",
    },

    # ══════════════════ AI 算力 / GPU ══════════════════
    {
        "id": "kaggle-gpu",
        "name": "Kaggle（免费 GPU）",
        "category": "ai-compute",
        "summary": "谷歌旗下，验证手机号后每周 30 小时 P100 或 2×T4 GPU，炼丹党零成本首选。",
        "quota": "每周 30 小时 GPU；通过身份验证后还有 TPU v3-8 每周 20 小时",
        "requirements": ["需手机验证", "免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.kaggle.com",
        "tips": "单次会话最长 12 小时；数据需要放 Kaggle Dataset 里。",
        "tags": "ai gpu 算力 免费 训练 深度学习 kaggle",
        "reviewed": "2026-09",
    },
    {
        "id": "google-colab",
        "name": "Google Colab",
        "category": "ai-compute",
        "summary": "最经典的免费 Jupyter 环境，偶尔能白嫖到 T4/P100。",
        "quota": "免费 GPU（受限，不保证类型）",
        "requirements": ["需谷歌账号", "免信用卡"],
        "china": "cn_no",
        "expiry": "长期",
        "url": "https://colab.research.google.com",
        "tips": "免费档有闲置断连机制；重要结果记得存 Google Drive。",
        "tags": "ai gpu 算力 免费 notebook jupyter colab 深度学习",
        "reviewed": "2026-09",
    },

    # ══════════════════ 云服务器 / 免费额度 ══════════════════
    {
        "id": "oracle-always-free",
        "name": "Oracle Cloud Always Free",
        "category": "cloud",
        "summary": "永久免费云主机里的天花板：2 核 ARM + 12GB 内存（2026-08 后下调），加 200GB 块存储、每月 10TB 出流量。",
        "quota": "A1 ARM 2 OCPU / 12GB + 2 台 AMD 1/8 OCPU / 1GB + 200GB 块存储 + 10TB/月出流量",
        "requirements": ["需信用卡验证（不扣费）"],
        "china": "cn_partial",
        "expiry": "永久免费",
        "url": "https://www.oracle.com/cloud/free/",
        "tips": "① 免费档 ARM 容量紧张，常需抢；② 闲置实例会被回收，跑个定时任务保活；③ 必须绑卡验证身份。",
        "tags": "云服务器 免费 vps 主机 永久 甲骨文 oracle arm",
        "reviewed": "2026-09",
    },
    {
        "id": "gcp-free-tier",
        "name": "Google Cloud 免费层",
        "category": "cloud",
        "summary": "1 台 e2-micro 永久免费（限特定区域），外加 BigQuery 每月 1TB 查询、Cloud Run 每月 200 万请求。",
        "quota": "e2-micro 1 台永久免费；Cloud Run 200 万次/月；BigQuery 1TB 查询/月",
        "requirements": ["需信用卡"],
        "china": "cn_no",
        "expiry": "永久（部分服务限区域）",
        "url": "https://cloud.google.com/free",
        "tips": "e2-micro 仅限 us-west1 / us-central1 / us-east1；出网流量要另算，注意流量费。",
        "tags": "云服务器 免费 vps 主机 gcp google 永久",
        "reviewed": "2026-09",
    },
    {
        "id": "aws-free-tier",
        "name": "AWS 免费层",
        "category": "cloud",
        "summary": "新账号 12 个月 t2.micro 750 小时/月 + Lambda 每月 100 万次 + S3 5GB。",
        "quota": "EC2 t2.micro 750 小时/月（12 个月）；Lambda 100 万次/月；DynamoDB 25GB",
        "requirements": ["需信用卡"],
        "china": "cn_partial",
        "expiry": "12 个月（部分永久）",
        "url": "https://aws.amazon.com/free/",
        "tips": "12 个月到期后会自动转按量计费，务必设日历提醒；这是最容易产生意外账单的一家。",
        "tags": "云服务器 免费 vps 主机 aws 亚马逊 试用",
        "reviewed": "2026-09",
    },
    {
        "id": "aliyun-trial",
        "name": "阿里云新用户试用",
        "category": "cloud",
        "summary": "新用户可领 1 核 2G 云服务器试用（通常 1~3 个月），经常有 99 元/年的轻量服务器活动。",
        "quota": "1 核 2G 试用 1~3 个月；轻量应用服务器常有低价年付活动",
        "requirements": ["需实名"],
        "china": "cn_ok",
        "expiry": "限时（1~3 个月）",
        "url": "https://free.aliyun.com",
        "tips": "到期会自动续费转付费，一定提前取消；学生可另看「阿里云高校计划」。",
        "tags": "云服务器 免费 vps 主机 阿里云 试用 国内",
        "reviewed": "2026-09",
    },
    {
        "id": "tencent-trial",
        "name": "腾讯云新用户试用",
        "category": "cloud",
        "summary": "新用户免费试用额度，轻量应用服务器经常有学生优惠。",
        "quota": "新用户试用额度和活动价（以官网为准）",
        "requirements": ["需实名"],
        "china": "cn_ok",
        "expiry": "限时",
        "url": "https://cloud.tencent.com/act/free",
        "tips": "同样注意到期自动续费；「腾讯云+校园」有学生专属优惠。",
        "tags": "云服务器 免费 vps 主机 腾讯云 试用 国内 学生",
        "reviewed": "2026-09",
    },
    {
        "id": "huawei-trial",
        "name": "华为云新用户试用",
        "category": "cloud",
        "summary": "新用户免费试用，部分产品有长期免费额度。",
        "quota": "以官网活动为准",
        "requirements": ["需实名"],
        "china": "cn_ok",
        "expiry": "限时",
        "url": "https://www.huaweicloud.com/free/",
        "tips": "注意到期续费；华为云对教育/学生场景有额外活动。",
        "tags": "云服务器 免费 vps 主机 华为云 试用 国内",
        "reviewed": "2026-09",
    },
    {
        "id": "cloudflare-workers",
        "name": "Cloudflare Workers",
        "category": "cloud",
        "summary": "边缘 Serverless，每天 10 万次请求免费，不需要信用卡。",
        "quota": "10 万次请求/天",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://workers.cloudflare.com",
        "tips": "和 Cloudflare 其他免费产品（R2 / D1 / Pages / Tunnel）组合起来能撑起一整套个人基础设施。",
        "tags": "云服务器 serverless 免费 边缘 cloudflare workers 无服务器",
        "reviewed": "2026-09",
    },

    # ══════════════════ 网站托管 / 部署 ══════════════════
    {
        "id": "vercel",
        "name": "Vercel",
        "category": "hosting",
        "summary": "前端项目免费部署，每月 100GB 流量，自动 CI/CD + 预览环境。",
        "quota": "每月 100GB 流量；个人项目免费",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://vercel.com",
        "tips": "国内访问其默认域名可能较慢，建议绑自己的域名。",
        "tags": "网站托管 部署 免费 前端 vercel 静态",
        "reviewed": "2026-09",
    },
    {
        "id": "netlify",
        "name": "Netlify",
        "category": "hosting",
        "summary": "静态站免费托管，每月 100GB 流量，和 Vercel 类似。",
        "quota": "100GB 流量/月，300 构建分钟/月",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.netlify.com",
        "tips": "表单、身份认证等增值功能也有免费额度。",
        "tags": "网站托管 部署 免费 静态 netlify",
        "reviewed": "2026-09",
    },
    {
        "id": "cloudflare-pages",
        "name": "Cloudflare Pages",
        "category": "hosting",
        "summary": "静态站托管，流量不限，每月 500 次构建。",
        "quota": "无限流量；500 次构建/月；100 个自定义域名",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://pages.cloudflare.com",
        "tips": "配合 Cloudflare CDN，国内访问通常比 Vercel 顺畅一些。",
        "tags": "网站托管 部署 免费 静态 cloudflare pages",
        "reviewed": "2026-09",
    },
    {
        "id": "github-pages",
        "name": "GitHub Pages",
        "category": "hosting",
        "summary": "最老牌的免费静态托管，推代码就发布，适合放文档和博客。",
        "quota": "公开仓库无限；每月 100GB 流量软限制",
        "requirements": ["需 GitHub 账号", "免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://pages.github.com",
        "tips": "国内访问 github.io 不稳定，建议绑自定义域名 + CDN。",
        "tags": "网站托管 部署 免费 静态 github pages 博客",
        "reviewed": "2026-09",
    },
    {
        "id": "render",
        "name": "Render",
        "category": "hosting",
        "summary": "免费 Web Service（有冷启动），适合跑个人后端服务。",
        "quota": "免费实例（闲置会休眠）",
        "requirements": ["免信用卡"],
        "china": "cn_no",
        "expiry": "长期",
        "url": "https://render.com",
        "tips": "免费实例闲置 15 分钟休眠，首次访问会慢十几秒。",
        "tags": "网站托管 部署 免费 后端 render paas",
        "reviewed": "2026-09",
    },
    {
        "id": "railway",
        "name": "Railway",
        "category": "hosting",
        "summary": "每月 5 美元免费额度，适合小型后端服务。",
        "quota": "每月 $5 额度",
        "requirements": ["需信用卡"],
        "china": "cn_no",
        "expiry": "每月重置",
        "url": "https://railway.app",
        "tips": "额度用完服务会停，不会自动扣费（但仍建议绑卡后设提醒）。",
        "tags": "网站托管 部署 免费 后端 railway paas",
        "reviewed": "2026-09",
    },

    # ══════════════════ 数据库 ══════════════════
    {
        "id": "supabase",
        "name": "Supabase",
        "category": "database",
        "summary": "开源版 Firebase，免费 PostgreSQL 500MB，还带认证、存储、实时订阅。",
        "quota": "500MB 数据库 + 5GB 带宽；最多 2 个项目",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://supabase.com",
        "tips": "免费项目闲置 7 天会被暂停，需要手动恢复。",
        "tags": "数据库 免费 postgresql postgres supabase 后端",
        "reviewed": "2026-09",
    },
    {
        "id": "neon",
        "name": "Neon",
        "category": "database",
        "summary": "Serverless PostgreSQL，免费 0.5GB，支持数据库分支（像 git 分支一样）。",
        "quota": "0.5GB 存储，10 个项目",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://neon.tech",
        "tips": "计算实例会休眠，冷启动有延迟。",
        "tags": "数据库 免费 postgresql serverless neon",
        "reviewed": "2026-09",
    },
    {
        "id": "mongodb-atlas",
        "name": "MongoDB Atlas",
        "category": "database",
        "summary": "行业标准的免费 MongoDB，512MB 永久免费。",
        "quota": "512MB 存储",
        "requirements": ["需信用卡（部分区域不需要）"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.mongodb.com/atlas",
        "tips": "选免费 M0 集群；注意默认开放 IP 白名单有安全风险，记得收紧。",
        "tags": "数据库 免费 mongodb nosql atlas",
        "reviewed": "2026-09",
    },
    {
        "id": "redis-cloud",
        "name": "Redis Cloud",
        "category": "database",
        "summary": "免费 30MB Redis，够做缓存和队列测试。",
        "quota": "30MB 内存",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://redis.io/cloud/",
        "tips": "容量很小，只适合开发/测试。",
        "tags": "数据库 免费 redis 缓存",
        "reviewed": "2026-09",
    },
    {
        "id": "upstash",
        "name": "Upstash",
        "category": "database",
        "summary": "Serverless Redis + Kafka，按请求计费，免费层够个人项目用。",
        "quota": "Redis 免费层 + Kafka 免费层",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://upstash.com",
        "tips": "按请求计费的模式，免费额度用完会拒绝而不是扣费。",
        "tags": "数据库 免费 redis kafka serverless upstash",
        "reviewed": "2026-09",
    },
    {
        "id": "turso",
        "name": "Turso",
        "category": "database",
        "summary": "边缘 SQLite，免费 9GB 存储，适合轻量应用。",
        "quota": "9GB 存储",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://turso.tech",
        "tips": "基于 SQLite，迁移成本低。",
        "tags": "数据库 免费 sqlite 边缘 turso",
        "reviewed": "2026-09",
    },
    {
        "id": "cloudflare-d1",
        "name": "Cloudflare D1",
        "category": "database",
        "summary": "Cloudflare 家的边缘 SQLite 数据库，免费 5GB。",
        "quota": "5GB 存储",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://developers.cloudflare.com/d1/",
        "tips": "和 Workers 配合最顺手。",
        "tags": "数据库 免费 sqlite cloudflare d1 边缘",
        "reviewed": "2026-09",
    },

    # ══════════════════ 对象存储 / 图床 ══════════════════
    {
        "id": "cloudflare-r2",
        "name": "Cloudflare R2",
        "category": "storage",
        "summary": "唯一真正做到出站流量免费的对象存储：10GB 存储 + 出站流量 0 费用。",
        "quota": "10GB 存储/月，出站流量免费",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.cloudflare.com/r2/",
        "tips": "兼容 S3 协议，可以直接套用现有 S3 代码；个人项目几乎不可能超。",
        "tags": "对象存储 免费 图床 s3 cloudflare r2 流量",
        "reviewed": "2026-09",
    },
    {
        "id": "backblaze-b2",
        "name": "Backblaze B2",
        "category": "storage",
        "summary": "10GB 免费存储 + 每天 10GB 出站流量，比 R2 存储更大。",
        "quota": "10GB 存储 + 10GB/天出站",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.backblaze.com/b2/cloud-storage.html",
        "tips": "和 Cloudflare 互联（Bandwidth Alliance）后出站也免费，是 R2 之外的好选择。",
        "tags": "对象存储 免费 图床 backblaze b2 备份",
        "reviewed": "2026-09",
    },
    {
        "id": "qiniu-free",
        "name": "七牛云免费额度",
        "category": "storage",
        "summary": "国内对象存储 + CDN，有长期免费额度（10GB 存储 + 每月 10GB CDN 流量）。",
        "quota": "10GB 存储 + 每月 10GB CDN 流量（以官网为准）",
        "requirements": ["需实名"],
        "china": "cn_ok",
        "expiry": "长期免费额度",
        "url": "https://www.qiniu.com",
        "tips": "国内做图床/CDN 最省事的选择之一；注意测试域名每月有流量限制。",
        "tags": "对象存储 免费 图床 cdn 七牛 国内",
        "reviewed": "2026-09",
    },
    {
        "id": "smms",
        "name": "SM.MS 图床",
        "category": "storage",
        "summary": "老牌免费图床，注册后直接用，适合 Markdown 配图。",
        "quota": "免费额度（有速率限制）",
        "requirements": ["免信用卡"],
        "china": "cn_ok",
        "expiry": "长期",
        "url": "https://sm.ms",
        "tips": "免费图床有失效风险，重要的图别只放这里。",
        "tags": "图床 免费 图片 存储 smms markdown",
        "reviewed": "2026-09",
    },

    # ══════════════════ 域名 / DNS / CDN ══════════════════
    {
        "id": "cloudflare-cdn",
        "name": "Cloudflare CDN + DNS",
        "category": "cdn-dns",
        "summary": "免费 CDN + DNS 不限域名数量 + 免费 SSL + 免费 DDoS 防护，个人开发者最优解。",
        "quota": "CDN 流量不限；DNS 域名数不限；免费 SSL",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.cloudflare.com",
        "tips": "免费版国内访问速度一般（节点在境外），但稳定性好。",
        "tags": "cdn 域名 dns 免费 ssl 证书 cloudflare 加速",
        "reviewed": "2026-09",
    },
    {
        "id": "cloudflare-tunnel",
        "name": "Cloudflare Tunnel",
        "category": "cdn-dns",
        "summary": "内网穿透利器：把本地端口暴露到公网，连注册都不用（快速隧道）。",
        "quota": "免费",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/",
        "tips": "本项目自己的公网入口就是用它做的（不稳定在随机域名会变）。",
        "tags": "内网穿透 免费 隧道 域名 cloudflare tunnel 反代",
        "reviewed": "2026-09",
    },
    {
        "id": "lets-encrypt",
        "name": "Let's Encrypt",
        "category": "cdn-dns",
        "summary": "免费 SSL 证书，被所有主流浏览器信任，行业标准。",
        "quota": "无限免费证书",
        "requirements": ["免信用卡"],
        "china": "cn_ok",
        "expiry": "长期（90 天自动续期）",
        "url": "https://letsencrypt.org/zh-cn/",
        "tips": "用 certbot 或 acme.sh 自动续期；国内服务器也能用。",
        "tags": "ssl 证书 https 免费 域名 letsencrypt",
        "reviewed": "2026-09",
    },
    {
        "id": "freenom-alt",
        "name": "免费二级域名（多种选择）",
        "category": "cdn-dns",
        "summary": "做测试站点时够用的免费域名：eu.org、dedyn.io、js.org 等。",
        "quota": "免费二级域名",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://nic.eu.org",
        "tips": "免费域名申请通常要人工审核（等几天）；不适合正式项目。",
        "tags": "域名 免费 二级域名 dns eu.org",
        "reviewed": "2026-09",
    },

    # ══════════════════ CI/CD / 代码托管 ══════════════════
    {
        "id": "github-actions",
        "name": "GitHub Actions",
        "category": "cicd",
        "summary": "公开仓库 CI/CD 完全免费无限分钟；私有仓库每月 2000 分钟。",
        "quota": "公开仓库无限；私有仓库 2000 分钟/月",
        "requirements": ["需 GitHub 账号", "免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://github.com/features/actions",
        "tips": "本项目的整条 CI/CD 流水线就跑在这里。",
        "tags": "ci cd 持续集成 免费 流水线 github actions",
        "reviewed": "2026-09",
    },
    {
        "id": "gitee",
        "name": "Gitee（码云）",
        "category": "cicd",
        "summary": "国内代码托管，访问快，私有仓库和 CI 有免费额度。",
        "quota": "免费私有仓库 + 免费 CI 额度",
        "requirements": ["需实名"],
        "china": "cn_ok",
        "expiry": "长期",
        "url": "https://gitee.com",
        "tips": "国内网络友好；开源项目发布也可考虑作镜像仓库。",
        "tags": "代码托管 免费 git 国内 gitee 码云 ci",
        "reviewed": "2026-09",
    },
    {
        "id": "codeberg",
        "name": "Codeberg",
        "category": "cicd",
        "summary": "非营利组织运营的开源代码托管，无限仓库 + 自带 CI。",
        "quota": "无限公开/私有仓库",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://codeberg.org",
        "tips": "基于 Forgejo，无广告无追踪。",
        "tags": "代码托管 免费 git codeberg ci",
        "reviewed": "2026-09",
    },

    # ══════════════════ 监控 / 告警 / 日志 ══════════════════
    {
        "id": "uptimerobot",
        "name": "UptimeRobot",
        "category": "monitor",
        "summary": "免费网站可用性监控，每 5 分钟探测一次，挂了发邮件/短信。",
        "quota": "50 个监控项，5 分钟间隔",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://uptimerobot.com",
        "tips": "最轻量的「我的站还活着吗」方案。",
        "tags": "监控 告警 免费 可用性 网站 uptimerobot",
        "reviewed": "2026-09",
    },
    {
        "id": "sentry",
        "name": "Sentry",
        "category": "monitor",
        "summary": "错误追踪，免费额度够个人项目（每月 5000 个错误事件）。",
        "quota": "5000 错误事件/月，1 个用户",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://sentry.io",
        "tips": "接入 SDK 后能自动捕获异常堆栈，比自己写日志好用得多。",
        "tags": "监控 错误追踪 免费 异常 sentry 日志",
        "reviewed": "2026-09",
    },
    {
        "id": "grafana-cloud",
        "name": "Grafana Cloud 免费层",
        "category": "monitor",
        "summary": "托管版 Grafana + Prometheus + Loki，免费额度可长期使用。",
        "quota": "10k 指标序列 + 50GB 日志/月（免费层）",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://grafana.com/products/cloud/",
        "tips": "不想自建 Prometheus 时的省事选择；本项目选择自建（更能学到东西）。",
        "tags": "监控 指标 日志 免费 grafana prometheus loki",
        "reviewed": "2026-09",
    },
    {
        "id": "betterstack",
        "name": "Better Stack",
        "category": "monitor",
        "summary": "日志 + 可用性监控，免费层带 10 个监控项和日志额度。",
        "quota": "10 个监控 + 日志免费额度",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://betterstack.com",
        "tips": "界面友好，适合当 UptimeRobot 的替代。",
        "tags": "监控 日志 免费 可用性 betterstack",
        "reviewed": "2026-09",
    },

    # ══════════════════ 邮件发送 ══════════════════
    {
        "id": "resend",
        "name": "Resend",
        "category": "email",
        "summary": "开发者友好的邮件 API，每月 3000 封免费。",
        "quota": "3000 封/月，100 封/天",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://resend.com",
        "tips": "要发到自己的域名需要配 DNS 记录（SPF/DKIM）。",
        "tags": "邮件 发送 免费 smtp 邮件api resend",
        "reviewed": "2026-09",
    },
    {
        "id": "sendgrid",
        "name": "SendGrid",
        "category": "email",
        "summary": "老牌邮件服务，免费每天 100 封。",
        "quota": "100 封/天",
        "requirements": ["需实名审核"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://sendgrid.com",
        "tips": "注册审核较严，可能需要说明用途。",
        "tags": "邮件 发送 免费 smtp sendgrid",
        "reviewed": "2026-09",
    },
    {
        "id": "brevo",
        "name": "Brevo（原 Sendinblue）",
        "category": "email",
        "summary": "每天 300 封免费邮件额度，是免费额度里较大的。",
        "quota": "300 封/天",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.brevo.com",
        "tips": "同时带营销邮件和 SMS 能力。",
        "tags": "邮件 发送 免费 smtp brevo sendinblue",
        "reviewed": "2026-09",
    },

    # ══════════════════ 登录 / 认证 ══════════════════
    {
        "id": "clerk",
        "name": "Clerk",
        "category": "auth",
        "summary": "开箱即用的登录组件，5 万月活用户免费。",
        "quota": "5 万 MAU",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://clerk.com",
        "tips": "前端几行代码就能加登录/注册/第三方登录。",
        "tags": "认证 登录 免费 用户管理 auth clerk",
        "reviewed": "2026-09",
    },
    {
        "id": "supabase-auth",
        "name": "Supabase Auth",
        "category": "auth",
        "summary": "和 Supabase 数据库打包的认证服务，免费额度大。",
        "quota": "随 Supabase 免费项目，5 万 MAU 级别",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://supabase.com/auth",
        "tips": "已经用 Supabase 的话直接用它，不用再引入新服务。",
        "tags": "认证 登录 免费 supabase auth 用户",
        "reviewed": "2026-09",
    },

    # ══════════════════ 开发工具 / 其他 ══════════════════
    {
        "id": "cloudflare-turnstile",
        "name": "Cloudflare Turnstile",
        "category": "devtool",
        "summary": "免费验证码替代品，无感验证，比 reCAPTCHA 更干净。",
        "quota": "免费无限",
        "requirements": ["免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://www.cloudflare.com/products/turnstile/",
        "tips": "国内用户也能正常加载（比 reCAPTCHA 强）。",
        "tags": "验证码 免费 安全 turnstile 人机验证",
        "reviewed": "2026-09",
    },
    {
        "id": "github-codespaces",
        "name": "GitHub Codespaces",
        "category": "devtool",
        "summary": "云端 VS Code，每月 120 核时免费，配好环境随时开工。",
        "quota": "120 核时/月 + 15GB 存储",
        "requirements": ["需 GitHub 账号", "免信用卡"],
        "china": "cn_partial",
        "expiry": "每月重置",
        "url": "https://github.com/features/codespaces",
        "tips": "适合在没有开发环境的设备上写代码；用 SSH 连进去也行。",
        "tags": "开发工具 免费 云端 ide vscode codespaces",
        "reviewed": "2026-09",
    },
    {
        "id": "cloudflare-email-routing",
        "name": "Cloudflare Email Routing",
        "category": "devtool",
        "summary": "用自己的域名收发邮件，免费转发到你的常用邮箱。",
        "quota": "免费无限转发",
        "requirements": ["需自己的域名", "免信用卡"],
        "china": "cn_partial",
        "expiry": "长期",
        "url": "https://developers.cloudflare.com/email-routing/",
        "tips": "做「admin@你的域名」这种专业邮箱地址最省钱的方式。",
        "tags": "邮箱 域名 免费 转发 email routing",
        "reviewed": "2026-09",
    },
    {
        "id": "jsdelivr",
        "name": "jsDelivr",
        "category": "devtool",
        "summary": "免费 CDN，直接从 npm / GitHub 提供静态资源，国内有节点。",
        "quota": "免费无限",
        "requirements": ["免信用卡"],
        "china": "cn_ok",
        "expiry": "长期",
        "url": "https://www.jsdelivr.com",
        "tips": "免费 CDN 里国内访问最稳的之一，适合放前端库文件。",
        "tags": "cdn 免费 jsdelivr 静态资源 前端",
        "reviewed": "2026-09",
    },
]


def as_list() -> list[dict]:
    """返回全部精选条目（浅拷贝，避免调用方误改模块常量）。"""
    return [dict(e) for e in ENTRIES]


def category_name(key: str) -> str:
    for k, name in CATEGORIES:
        if k == key:
            return name
    return key
