"""把数据从 SQLite 搬到 PostgreSQL（一次性迁移工具）。

为什么要有它：切数据库最大的风险是**历史数据丢了** ——
1335 条资源快照、变更记录、我的领用记录都在那个 SQLite 文件里。
没有迁移工具就只能重新采集，变更历史永久丢失。

用法（在集群里跑一次性 Job）：
    python -m app.cli migrate --from /data/radar.db

判重策略：迁移可重复执行（幂等）。
- snapshots / entries / changes / link_checks：按主键判重，已存在就跳过
- mine / seen_entries：按主键 upsert（用现有值覆盖）

⚠️ **迁移后必须重置自增序列**（见 `_reset_sequences`）——
这是迁 PostgreSQL 最经典的坑，而且我自己踩了：为了保留原 id 会**显式插入 id**，
但 PG 的 `GENERATED BY DEFAULT AS IDENTITY` 序列**不会因此前进**，
于是下一次自增插入会用已被占用的 id → 主键冲突。

线上的真实表现（2026-10-02 才被发现）：
- `link_checks` 迁移了 88 行（id 1~88），但序列停在 1
- 每天巡检插入第一条就冲突失败，**而每次失败只让序列前进 1**
- 所以整整 10 天巡检都在失败，而且按这个速度还要 62 天才能"自愈"
- 采集任务也失败过 2 次，直到序列爬到 max(id) 才自己好了（掩盖了问题）
"""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any

from . import db, database

# (表名, 主键列, 是否用 upsert)
TABLES: list[tuple[str, list[str], bool]] = [
    ("snapshots", ["id"], False),
    ("entries", ["snapshot_id", "entry_key"], False),
    ("changes", ["id"], False),
    ("mine", ["entry_id"], True),
    ("link_checks", ["id"], False),
    ("seen_entries", ["entry_id"], True),
]

# 带自增 id 的表 —— 迁移后要把序列对齐，否则后续插入一定冲突
AUTO_ID_TABLES = ["snapshots", "changes", "link_checks"]


def _reset_sequences(dst) -> dict[str, int]:
    """把自增序列对齐到表里的实际最大 id。**只在 PostgreSQL 下有效。**

    为什么必须做：PG 的序列和表数据是**两个独立的东西**。
    显式插入 id（迁移必然这么做）不会推进序列，序列就留在原地，
    之后任何"不指定 id 的插入"都会拿到一个已被占用的值。

    这个函数是幂等的，重复执行无副作用。
    """
    result: dict[str, int] = {}
    for table in AUTO_ID_TABLES:
        row = dst.execute(
            f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
            f"COALESCE((SELECT MAX(id) FROM {table}), 1)) AS v"
        ).fetchone()
        if row is not None:
            result[table] = row["v"]
    dst.commit()
    return result


def _cols(conn_sqlite: sqlite3.Connection, table: str) -> list[str]:
    return [r[1] for r in conn_sqlite.execute(f"PRAGMA table_info({table})")]


def _table_exists(conn_sqlite: sqlite3.Connection, table: str) -> tuple[bool, str | None]:
    """判断源库里有没有这张表，**并保留真实的失败原因**。

    ⚠️ 这里踩过一个坑：最初只写了 `try: PRAGMA table_info ... except DatabaseError:
    skipped("源库里没有这张表")`，结果把一个完全不同的问题（SQLite 是 WAL 模式，
    只读挂载下打开失败）误报成"表不存在"，排查时被误导了很久。
    现在把底层异常信息一起带出来。
    """
    try:
        rows = list(conn_sqlite.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name=?", (table,)
        ))
        return bool(rows), None
    except sqlite3.DatabaseError as exc:
        return False, f"打开源库失败: {exc}"


def migrate(source: str | Path) -> dict[str, Any]:
    src_path = Path(source)
    if not src_path.exists():
        raise FileNotFoundError(f"源库不存在: {src_path}")

    # 提示：SQLite 若处于 WAL 模式，**只读挂载会打开失败**（WAL 恢复需要写权限）。
    # 集群里跑迁移时，先把文件复制到可写目录再迁（见 k8s 里的一次性 Job）。
    src = sqlite3.connect(src_path)
    src.row_factory = sqlite3.Row
    dst = db.connect()

    report: dict[str, Any] = {"source": str(src_path), "tables": {}}
    try:
        for table, pk, upsert in TABLES:
            exists, reason = _table_exists(src, table)
            if not exists:
                report["tables"][table] = {"skipped": reason or "源库里没有这张表"}
                continue
            cols = _cols(src, table)
            rows = [dict(r) for r in src.execute(f"SELECT * FROM {table}")]
            if not rows:
                report["tables"][table] = {"rows": 0, "inserted": 0}
                continue

            placeholders = ", ".join("?" for _ in cols)
            collist = ", ".join(cols)
            if upsert:
                updates = ", ".join(f"{c} = excluded.{c}" for c in cols if c not in pk)
                sql = (
                    f"INSERT INTO {table} ({collist}) VALUES ({placeholders}) "
                    f"ON CONFLICT ({', '.join(pk)}) DO UPDATE SET {updates}"
                )
            else:
                # 幂等：主键冲突就跳过（PG 支持 DO NOTHING，SQLite 3.24+ 也支持）
                sql = (
                    f"INSERT INTO {table} ({collist}) VALUES ({placeholders}) "
                    f"ON CONFLICT ({', '.join(pk)}) DO NOTHING"
                )

            inserted = 0
            for r in rows:
                cur = dst.execute(sql, [r.get(c) for c in cols])
                if cur.rowcount and cur.rowcount > 0 and not upsert:
                    inserted += 1
            dst.commit()
            report["tables"][table] = {"rows": len(rows), "inserted": inserted if not upsert else len(rows)}

        # ⭐ 关键一步：把自增序列对齐到实际最大 id。
        # 不做这一步，迁移后所有「不指定 id 的插入」都会主键冲突
        # （线上真实事故：巡检任务连续 10 天失败）。
        if database.using_postgres():
            report["sequences_reset"] = _reset_sequences(dst)

        # 迁移后做个基本校验：条目数对不对得上
        latest = dst.execute("SELECT MAX(id) AS id FROM snapshots").fetchone()
        if latest and latest["id"] is not None:
            cnt = dst.execute(
                "SELECT COUNT(*) AS c FROM entries WHERE snapshot_id = ?", (latest["id"],)
            ).fetchone()
            report["verify"] = {"latest_snapshot_id": latest["id"], "entries_of_latest": cnt["c"]}
    finally:
        src.close()
        dst.close()

    return report
